### ISSUE TITLE
采集时钟部分采集品无法显示地图

### ISSUE THREAD

**Issue by Tanimodori** [InfSein/hqhelper-dawntrail#62]
##截图

![image](https://github.com/user-attachments/assets/20580ac4-901f-4230-a725-a4f002500f58)
![image](https://github.com/user-attachments/assets/4cd4426f-eeae-4441-a75a-9001321e8e24)

## 适用版本

此bug同时影响客户端和网页版本

当前网页版本：2.0.12
当前客户端版本：v4
国服数据版本：7.01
国际服数据版本：7.05

## 复现步骤

1. 打开`实用工具`-`食药计算`
2. 在`[1]挑选食药`中选中`版本7.05`，在`烤犎牛肉串(暂译)`右边输入1添加一份需求
3. 在`[2]查看统计`中的`常规采集品`中，鼠标悬停在`油橄榄`上可以发现没有地图位置，但是`高山岩盐`是有地图位置的

**Comment by InfSein** [comment]
之前在 [2.0.8](https://github.com/InfSein/hqhelper-dawntrail/releases/tag/v2.0.8) 版本实装地图功能的时候因包体限制等考虑，只实装了7.0的野外地图

后续会考虑实装旧版本的地图

**Comment by Tanimodori** [comment]
个人还是希望能够统一用户体验的，划一下就能看到去哪里采集是个很方便的功能，新版本食药不可避免地要去旧版本地图采集，如果还要去找坐标、翻采集笔记、查Wiki都很麻烦。体积过大的话可以试试压缩地图图片，毕竟展示范围很小。
