### ISSUE TITLE
跳转至BestCraft模拟制作时可能需要提示切换数据源

### ISSUE THREAD

**Issue by Tnze** [InfSein/hqhelper-dawntrail#72]
当跳转到国服数据源不包含的配方时，获取配方信息会出错。需要用户提前切换到国际服数据源

**Comment by InfSein** [comment]
其实我感觉bestcraft那边把提示从 `SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON` 改成 `无数据，请尝试切换成国际服数据源` 会好一点。。我这里加的话有点不知道咋加

或者可以考虑提供一个参数接口，例如`?recipeId=xxx&dataSource=global`，传递对应参数时自动切换数据源，或是临时使用国际服数据源这样

**Comment by Tnze** [comment]
`SyntaxError...` 那个提示其实是因为服务端那边错误处理的比较随意，导致接口返回了Web框架默认的500错误界面，前端尝试将其作为JSON数据解析的时候报了语法错误。

加一个参数接口用于切换数据源技术上是可行的，但是我担心用户的数据源设置被偷偷换掉之后，不知道去哪里改回来。不改设置的数据源 而只对当前跳转的配方指定数据源，现在不是很容易实现。

---

问题不大，先讨论讨论，反正马上要更新了，这些跳转失败的数据很快就会补上。

**Comment by Tnze** [comment]
> 其实我感觉bestcraft那边把提示从 `SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON` 改成 `无数据，请尝试切换成国际服数据源` 会好一点。。我这里加的话有点不知道咋加

暂且这样改了

**Comment by InfSein** [comment]
嗯，应该差不多够用了
